### ISSUE TITLE
Cells do not derive from "pyNN.standardmodels.cells", missing "default_parameters" attribute

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#120]
In contrast to the standard PyNN backends and the ESS backend, sPyNNaker cell types do not inherit from their `pyNN.standardmodels.cells` counterpart and thus do not expose all the attributes one expects from a PyNN cell, such as `default_parameters`.

Sample code:

    import pyNN.spiNNaker
    pyNN.spiNNaker.IF_cond_exp.default_parameters

Results in:

    AttributeError: type object 'IFConductanceExponentialPopulation' has no attribute 'default_parameters'

Where the expected result is something along the lines of

    {'cm': 1.0,
     'e_rev_E': 0.0,
     'e_rev_I': -70.0,
     'i_offset': 0.0,
     'tau_m': 20.0,
     'tau_refrac': 0.1,
     'tau_syn_E': 5.0,
     'tau_syn_I': 5.0,
     'v_reset': -65.0,
     'v_rest': -65.0,
     'v_thresh': -50.0}

In my opinion the best solution would be to derive from the correct base class to eliminate any surprising behaviour of the cell classes. If you really have to go on using duck typing please do it correctly by exposing the entire interface.

**Comment by apdavison** [comment]
This is largely my fault, since there is no formal definition of the PyNN API, so it is difficult for backend developers to know which parts of the interface are required and which are implementation details.

I plan to rectify this in PyNN 0.9 both by writing documentation and by defining abstract base classes (rather than the current base classes which are part of the "common" implementation, and which include parameter translation machinery which the SpiNNaker backend doesn't use).

(I confirm that the `default_parameters` attribute *is* part of the API).

**Comment by alan-stokes** [comment]
fixed in pynn_changes branch, is awaiting other functionality to be done before pull request and merging into master.

**Comment by alan-stokes** [comment]
merged into master. will be in the arbitiriary release. issues being closed accordingly.
