### ISSUE TITLE
Allow recording spikes from SpikeSourceArray

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#122]
Calling "record" on a SpikeSourceArray-Population causes the exception

      File "/localhome/nmpidemo/RemoteSpiNNaker/temp/job9038993244753782756.tmp/lib/simulation_pyNN_v7.py", line 40, in execute
        inputPopulation.record()
      File "/localhome/nmpidemo/sPyNNaker/sPyNNaker/spynnaker/pyNN/models/pynn_population.py", line 377, in record
        raise Exception("This population does not support recording!")
    Exception: This population does not support recording!

Whereas it is nice to (for once) have such a nice and clear error message, I see no reason why this should not be supported, with the simplest implementation being to just copy the "spike_times" to the record buffer. Maybe issue a warning, that you did not record the spike times from the hardware itself.

Whatever you do, just don't crash. There is no point in having an abstraction layer such as PyNN if every implementation behaves differently (please do not take my frustration personally)...

**Comment by alan-stokes** [comment]
Hi Stockel, 

the reason we crash is because there is no perfect way to do this currently. Extracting the spike times from the "record buffer" (to which im assumign you mean the ram of the host machine) does not give you the confidence that those spikes were actually sent. On the flip side, because the spike source array no longer has a SDRAM cap (due to a piece of functionality with moves chunks of data, called a buffer, from the host to the machine during exeuction runtime, as its needed) this means we do not know how much memory to allocate it for recording the events in the same way as we currently do. There is a piece of work which takes the flip coin of moving buffers of data in, to moving buffers out (named buffered out and is issue #15), which would solve this problem entirely, but alas this is not finished, nor will it be in the arbitiary release. 

What I'm starting as a ...... bodge/attempt to loosen the limitation........ is to allow recording of the spike source array. But only if the amount of events the spike source array is expected to output can be recorded on the spinnaker machine. This means a spike soruce array that has a load of events, and is set to record, will fail due to lack of memory issues, whereas a sike source array with a reasonable amount of spikes with recording may work. This wont put a cap on the number of events the spike source array can output when not set to record. I hope this will at least give you guys and galls some relief till the buffered out functionality is supported and released.

**Comment by astoeckel** [comment]
Hi Alan,

yes, this sounds like a viable solution and is perfectly fine with me.

Thank you for your efforts!

Andreas

**Comment by alan-stokes** [comment]
Changes are in place within the #recordable_spike_source_array branch. It is awaiting review and merging into master before it is possible to be released. Its highly likely it will get into the Arbitrary release, but cannot make any promises.

**Comment by alan-stokes** [comment]
Rowley has merged this within the master branch, will be introduced in our bug release of arbitiary this week. 

therefore closing issue
