### ISSUE TITLE
Observation Point During Simulation 

### ISSUE THREAD

**Issue by WemboLi** [SpiNNakerManchester/sPyNNaker#130]
Dear all,
I am using spinnaker platform for machine learning purposes. And I am wondering that apart from using spynnaker.pyNN.run() to start the simulation, record the spikes of the whole simulation time and do analysis afterwards, is there a way of observing the spikes in one internal(e.g. I want to see the spikes from 100ms to 200ms in a 1000ms long simulation)? I wish I can use the observation result to make learning decisions. 

Furthermore, if it is not permitted to observe result in simulation process, is it possible to call spynnaker.pyNN.run() for multiple times to observe different neuron firing pattern?

Thanks for your reading.

**Comment by AlexRast** [comment]
Hi Wenbo,

I'd like to understand a bit about how you want to use the observed result to 
make learning decisions. Are you running an external process on a PC that 
inspects the spikes and then presents some input back to SpiNNaker? If so that 
would easily be done using a live packet gatherer and a spike injector (to send 
back the tuning spikes from your external process). Are you wanting yourself to 
visualise the spikes live? This is also achievable with the Visualiser we have; 
currently it is still fairly limited in functionality but you could extend it if 
need be. Or are you planning on using the spikes in some other way? Please give 
us a few more details on how you plan your application to work.

Thanks,

Alex Rast.

**Comment by WemboLi** [comment]
Hi Alex,
I will try my best to explain to you, things are like this: I simulated a neuron network on spinnaker and inject spikes to the neuron population using the model "SpikeSourceArray".(Spike time is generated from recorded eDVS data including patterns of  moving objects, e.g. left to right and right to left).Then I train the neuron network with STDP rule and record the firing neuron index for different patterns. After training, I use "SpikeSourceArray" model again to check if the neuron network can recognize the pattern like moving from left to right in eDVS data. (By recognizing, I mean the same set of neurons only fire for a specific pattern) The final goal is to use the firing neurons information to drive a motor, namely, if the neuron fires indicate that there is object moving from left to right then the motor will move from left to right. Therefore, I need the neuron spike information in one interval instead of the whole simulation to decide the object movement and respond accordingly.

I hope the explanation can help you understand my problem.  Again, thanks for your time!

**Comment by AlexRast** [comment]
On 17/08/15 23:37, Wenbo Li wrote:
> Hi Alex,
> I will try my best to explain to you, things are like this: I simulated a neuron
> network on spinnaker and inject spikes to the neuron population using the model
> "SpikeSourceArray".(Spike time is generated from recorded eDVS data including
> patterns of moving objects, e.g. left to right and right to left).Then I train
> the neuron network with STDP rule and record the firing neuron index for
> different patterns. After training, I use "SpikeSourceArray" model again to
> check if the neuron network can recognize the pattern like moving from left to
> right in eDVS data. (By recognizing, I mean the same set of neurons only fire
> for a specific pattern) The final goal is to use the firing neurons information
> to drive a motor, namely, if the neuron fires indicate that there is object
> moving from left to right then the motor will move from left to right.
> Therefore, I need the neuron spike information in one interval instead of the
> whole simulation to decide the object movement and respond a ccording ly.

As described here I'm not seeing why you need the firing information in 
real-time instead of after the simulation. As you have described it here, it 
appears that the only points where you are actually using the spike information 
*externally* are when you record the firing index during training and after 
training. In both of those cases it would seem because you are using a 
SpikeSourceArray you can identify the onset and offset times of different 
patterns a priori, and thus an offline record of the spikes would enable you to 
determine if identical indices were firing. You can compare neuron indices 
firing at the specified onset and offset times for a given pattern and make sure 
they match.

But it sounds like that's not what you're *actually* doing, so I think I need a 
more detailed description; in particular one which specifies when spike 
information is actually being used by dynamic processes - and what those 
processes do concretely.

**Comment by WemboLi** [comment]
Sorry about my a little vague discription. To make it more specific, I am just using post-trained neuron network for detection of movement of 200ms data and there are consecutive 200ms data segments in the simulation. What I need to do is decide the move pattern every 200ms and output a signal for the motor. However, I find it impossible to get spike during the simulation cuz once it has been started I have to wait until the end to see the spike result. So I am wondering if there exists a method for *real time* spike info in the simulation.

THXs！
Wenbi

**Comment by AlexRast** [comment]
OK, so you just need the output to send to your motor transducers, from what it 
sounds like. This is straightforward and what you use is the pyNN extension 
activate_live_output_for(population) in your pyNN script. This command actually 
has quite a few potential settings that you can use if you need some fancy 
output spike format but in general you can leave most parameters as default. You 
can see the complete list of potential arguments in __init__.py in the 
spynnaker_external_devices_plugin.pyNN module.

The instantiation will create a database containing among other things a map of 
neuron ID (the keys that you will receive from SpiNNaker) to population. Your 
application needs to communicate with this database to fetch the mapping at the 
start of the simulation and then decide what it wants to do with keys received. 
spynnaker_live_spikes_connection in 
spynnaker_external_devices_plugin.pyNN.connections can automate much of this 
process for you - it lets you specify a callback function which can be almost 
anything, associated with a population, so that when spikes are received from 
that population your callback will activate and do whatever. It's also possible 
in principle to "roll your own" handler for this e.g. in a C application 
although I would try first with a spinnaker_live_spikes_connection. The key 
thing is the communication with the database so that the spikes can be decoded 
appropriately by the receiving application.

You also need to add a few settings to the spynnaker.cfg file in the directory 
of your pyNN script (do not edit the top-level global one!). In section 
[Recording] set live_spike_port = {port_number} and live_spike_host = {host IP 
address}. In section [Database] set create_database = True, wait_on_confirmation 
= True, send_start_notification = True, create_routing_info_to_neuron_id_mapping 
= True. These set up your system to receive spikes and communicate with the 
database; the port number and host IP you should set to whatever your receiver 
is on or is expecting - spiNNaker will attempt to send to this location.

The script spike_io.py has a reasonable example of all this in action, and also 
here is a sample spynnaker.cfg from my machine which has everything I just 
discussed (plus various other settings you don't need to worry about for your 
system)

On 18/08/15 09:50, Wenbo Li wrote:
> Sorry about my a little vague discription. To make it more specific, I am just
> using post-trained neuron network for detection of movement of 200ms data and
> there are consecutive 200ms data segments in the simulation. What I need to do
> is decide the move pattern every 200ms and output a signal for the motor.
> However, I find it impossible to get spike during the simulation cuz once it has
> been started I have to wait until the end to see the spike result. So I am
> wondering if there exists a method for *real time* spike info in the simulation.
>
> THXs！
> Wenbi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpiNNakerManchester/sPyNNaker/issues/130#issuecomment-132122883>.
>

[Logging]
# ------
# Logging levels are as specified for the Python logging module.
# Listing a module below overrides the default logging level for that module
# and its children (unless they are also overridden).
#
# e.g., the following sample would set the default level to info, but display
# debug messages for pacman103.front.pynn, and only display warning messages
# for pacman.core
#
#     default = info
#     debug = front.pynn
#     info =
#     warning = core
#     error =
#     critical =
#
# The ```instantiate``` option determines whether front-ends set up loggers.
# If ```instantiate``` is True then users do not need to set up their own
# loggers.  If it is False, then users need to instantiate a logger at the top
# of each script, this is simply achieved by inserting the following lines at
# the top of the file.
#
#    include logging
#    logger = logging.basicConfig()
#
instantiate = True
default = info
debug =
info =
warning =
error =
critical =

[Reports]
# If reportsEnabeld is false, no text reports are written.
# writeTextSpecs: If True, produce text version of each Data Spec,
#                 in reports/dataSpec directory
# writeRouterReports: If True, each router file is written in
#                 text format to reports/routers
reportsEnabled = True
writeTextSpecs = False
writePartitionerReports = True
writePlacerReports = True
writeRouterReports = True
writeRouterInfoReport = True
writeRouterDatReport = False
writeTransceiverReport = True
writeProvanceData = True
writeTagAllocationReports = True
outputTimesForSections = True
writeReloadSteps = True
# options are DEFAULT (hard coded location) or a file path
defaultReportFilePath = /home/P06/rasta/folders/prg/gamma_package_103/reports
# options are DEFAULT, TEMP, or a file path
#NOTE ***that for bespoke file paths, folders will not be automatically deleted***
defaultApplicationDataFilePath = /home/P06/rasta/folders/prg/gamma_package_103/data_binaries
max_reports_kept = 10
max_application_binaries_kept = 10

[Simulation]
# Maximum spikes per second of any neuron (spike rate in Hertz)
spikes_per_second = 30

# The number of standard deviations from the mean to account for in
# the ring buffer
ring_buffer_sigma = 5

[Machine]
#-------
# Information about the target SpiNNaker board or machine:
# machineName: The name or IP address of the target board
# down_cores: Cores that are not working
# down_chips: Chips that are not working
# core_limit: The maximum number of cores to use on the board
# machineTimeStep: Internal time step in simulations in usecs)
# timeScaleFactor: Change this to slow down the simulation time
#                  relative to real time.
# appID:           Used by sark to identify the user's application.
machineName     = 130.88.196.21
virtual_board = False
virtual_board_x_dimension = 0
virtual_board_y_dimension = 0
requires_wrap_arounds = False
# format is ,,:,,:
down_cores = None
down_chips = None
core_limit = 16
machineTimeStep = 1000
timeScaleFactor = None
appID = 30
tryReboot = True
# version should be the type of board = SpiNN-<version>
version = 3

[Routing]
# ------
# AM: THIS NEEDS REVISITING
# algorithm: {BasicDijkstra}
algorithm = BasicDijkstra
generate_graphs = False
graphs_output_file = tmp
#directories to search for algorithums. list in order

[Placer]
#-------
# algorithm: {Radial, Basic, ConnectiveBased}
algorithm = Radial

[TagAllocator]
#---------
# algorithm: {Basic}
algorithm = Basic

[Partitioner]
# algorithm: {Basic, PartitionAndPlace}
algorithm = PartitionAndPlace

[KeyAllocator]
# algorithm: {Basic, MallocBased}
algorithm = MallocBased

[SpecExecution]
#-------------
# specExecOnHost: If True, execute specs on host then download to SpiNNaker
#                 False not yet support, where specs are downloaded
#                 to SpiNNaker and then executed.
specExecOnHost = True

[MasterPopTable]
# algorithm: {2dArray, BinarySearch, HashTable}
generator = BinarySearch


[Recording]
#---------

# Uncomment the following to change from the defaults
live_spike_port = 17895
live_spike_host = localhost
live_spike_tag = 1

[Buffers]
receive_buffer_port = 17896
receive_buffer_host = 0.0.0.0

[Execute]
run_simulation = True
load = True
run = True

[Mode]
#mode = Production or Debug
mode = Production

[Threading]
dsg_threads = 5

[Database]
create_database = True
wait_on_confirmation = False
send_start_notification = True
create_routing_info_to_neuron_id_mapping = True
listen_port = 19998
notify_port = 19999
notify_hostname = localhost

**Comment by WemboLi** [comment]
Hi Alex, 
Thanks for your patient guidance. I am a little bit about the scripts in spike_io.py as it is abstract compared to other neuron model examples, where do you get the received spikes info from the neuron population?  Is it here in the add_receive_callback? 

def receive_spikes(label, time, neuron_ids):
    for neuron_id in neuron_ids:
        print_condition.acquire()
        print "Received spike at time", time, "from", label, "-", neuron_id
        print_condition.release()

# Set up the live connection for sending and receiving spikes
if not using_c_vis:
    live_spikes_connection = SpynnakerLiveSpikesConnection(
        receive_labels=["pop_forward", "pop_backward"],
        send_labels=["spike_injector_forward", "spike_injector_backward"])

    # Set up callbacks to occur when spikes are received
    live_spikes_connection.add_receive_callback("pop_forward", receive_spikes)
    live_spikes_connection.add_receive_callback("pop_backward", receive_spikes)"

How can I process the neuron firing info for following decision？

**Comment by alan-stokes** [comment]
Hi Wembo, 

So using the spike_io.py script as an example, lines 153 to 157 handle the processing of the live spike feed. It recieves as input parameters 1. The label of the population that fired, 2. the timestamp of when that population fired, and 3. the neuron ids (as a list) of neurons that spiked at the time. You can do any processing you wish on this, but be aware that itll be fired whenever the host receives spikes from either of the pop_forward or pop_backwards populations. 

There is a spinnaker workshop which is advertised here: https://groups.google.com/forum/#!topic/spinnakerusers/8sEh5UqcsgM
Coming to this would allow you direct access to myself, Alex and the rest of the software team. Theres a new release of the software for this workshop, which simplifies some of the interfaces you'll need for your motor.
Finally, theres a collection of lab exercises which will hopefully give you a strong hold of how live packet retrival and injection are done in the sPyNNaker interface. Id sersiously advise you come to this workshop.

and finally, It may be worth you moving over to the spinnaker user google group (https://groups.google.com/forum/#!forum/spinnakerusers) for these kind of questions, as the google user group is supported by all users of the spinnaker software, and therefore theres a bigger collection of protential help there.

**Comment by WemboLi** [comment]
Thanks Alan！ I will try to use it for real time application. 
Regards！
Wenbo

**Comment by AlexRast** [comment]
To add to what Alan said, as noted there is the initial setup of the 
SpynnakerLiveSpikesConnection which handles the database interface and the event 
processing. As you have noted too there is the add_receive_callback - what this 
does is declare to the SpynnakerLiveSpikesConnection what it should do with a 
spike when received.

Your callback could in principle do just about anything - you can for instance 
send it on to a C process which interfaces with your motor, so you're not 
limited to Python functions like the receive_spikes callback you see in 
spike_io. You should try to make the callback efficient, though, or else you 
might run into problems trying to service lots of spikes. It's probably a good 
idea for example for your callback to buffer multiple spikes and process them as 
a batch rather than handle each one individually, if you're expecting lots of 
spikes back in a short time window.
