### ISSUE TITLE
Read out current membrane potential?

### ISSUE THREAD

**Issue by Scaatis** [SpiNNakerManchester/sPyNNaker#176]
It seems it is not currently possible to read out the current membrane potential of one or more cells, except by recording potential and taking the most recent value.

But I think it is possible to read memory from spiNNaker via sdp. Could that feature be used to read out current membrane potential?

**Comment by rowleya** [comment]
This could be done - you can simply read the region storing the neural parameters.

Do you have some behaviour that depends on the membrane potential over the spike activity?

**Comment by Scaatis** [comment]
Yes -- this is the in fact the main way that the neurorobotics platform reads activity from the network. I will send you a detailed email later with results from my first test.

**Comment by rowleya** [comment]
OK - I would certainly be interested in hearing how this works.  Generally, we communicate using spikes, as membrane potential is updated every timestep, but spikes occur less often.

**Comment by Scaatis** [comment]
I'm looking into this right now and my problem ist that the membrane voltage is stored in a different area of memory according to the neuron model. So I suppose the neuron application has to be made to respond to a new SDP packet. My previous attempt at this was ... less than successful.

Do you see a different way of doing it?

**Comment by rowleya** [comment]
It is possible to do as a single read:
The neuron parameters are stored in a single region, and this is the same for every neuron model, the only difference being the amount of data.  You can read the whole of this region, and then pass the data to the python part of that model for processing, from which it can extract the data (or else you can use the get_neuron_parameters to get the spec of the parameter region for the neuron and then read it appropriately, though this might actually be slower but more general).

As multiple reads:
The alternative is that you can read the parts of the data back that you need to.  This could be done as quickly, since the whole data region is ~10KB for 256 neurons, so you would need ~40 reads of 256 Bytes each (256 is the maximum data per packet).  If you read the V for each neuron, you would need 256 reads of 4 Bytes each, so more reads, but less data per read.  To do this efficiently, you would need to use the SpiNNMan process system, which can send multiple requests before processing responses.  This doesn’t currently work properly on multiple boards, but will in the near future.  This would require a bit more work, as I don’t think this interface is correctly exposed just now!

**Comment by Scaatis** [comment]
The way I envision it is that at the beginning of the simulation, the neuron model detects changes (similar to how a population does) and if there are some, writes them to SpiNNaker. At the end of the simulation, the current values are read back from the board (maybe each neuron model can specify which values it wants to read/write back). That way, between runs you have a model in python that you can work with as you please and as long as you don't make changes that require mapping, you can just call run again and the board will be updated.
If possible, I would like to implement this in a way that is transferrable to SpikeSourcePoisson, so that can work in a similar way.

**Comment by rowleya** [comment]
This should be possible, and it meets another goal of ours (to be able to update neuron parameters between runs).  The only issue is if the user calls reset – you will need to keep the initial values somewhere as well.  In this case you may as well read the full region back rather than just the membrane voltages, as this stores the current values of the neuron parameters as well (although these don’t usually change ;).

Be aware when reading the region that there are also some other things at the start of it, including the number of neurons.

**Comment by alan-stokes** [comment]
just to add. the storing of the original parameters might not be necessary. the reset functionality loads the application data again during the next run. Therefore the original neuron parameters are in that application data file and will be loaded anyhow.

This does open up issues with the changing the application graph or changes that require mapping, as that changes the application files, as well as a feck load of other stuff (such as remapping recorded data etc), thus the reason why if it detects this, it currently raises an error. 

One thing to note, is that these parameters are only ever read during the original init in the c code, and the commands for updating the runtime etc don't go though that init again. You'd need to either reload the binary to force it to reread these params (not the best idea) or add a new command to the list which gets the c code to reread this data region again. 
Alan

**Comment by rowleya** [comment]
I think this change is only meant to affect the parameters of the neurons themselves, not the number, so remapping shouldn't be required.  You are right that we would have to be careful about where the changes are pushed to i.e. if they are pushed to SDRAM, a read would be required, but if they are sent via SDP messages, they could be altered in DTCM; using SDP to update DTCM directly also means that, as Alan says, the original values are left in SDRAM if a reset is done, you can just copy the values from there.

Regarding the Poisson source, I did create a version that you could update using SDP messages.  This is in a very out-of-date branch, but the changes to the Poisson itself might still be mostly easy to merge.  The branch is called poisson_live_rate:
https://github.com/SpiNNakerManchester/sPyNNaker/tree/poisson_live_rate

This alters the parameters so that you can change a source between being fast or slow as I remember it, and I think it also supports 0-rate sources (i.e. not sending spikes).

**Comment by rowleya** [comment]
This is the commit:
https://github.com/SpiNNakerManchester/sPyNNaker/commit/c55d38e5d1a67a929364f56aeca2265847028fe0

I note that this uses reverse ip tag, which won't work if you have too many of them (you run out of tags).  That said, if you remove this need, you can just use SDP if you know the placement of the subvertices.

**Comment by Scaatis** [comment]
I feel a bit uncomfortable just adding to the SDP specification, that kind of seems like your show. I think there should probably be two messages, GET_PARAM and SET_PARAM, but how should the parameter be identified? (ideally I would like this to not be specific to membrane voltage)

As for reset, would it be appropriate to just reload the binary which would then reload everything from SDRAM?

**Comment by alan-stokes** [comment]
Hi Felix, the get command is a bit confusing. These parameters don't change during normal operation, and as you'll have changed the param in the python, the getter can just return the value from python. The setter is needed, but I'm thinking that the most general is a trnasciver write memory, and then the sdp message just asks the modle to reread the sdram. this then means we might be able to do reset without reloading the binaries as well. changing dtcm means that there's a mismatch between dtcm and sdram, and im not too comfortable with that for future maintenance.

**Comment by Scaatis** [comment]
A general get command could be overkill, but the membrane voltage does change during normal operation, and I have not set it via python, so some kind of get is necessary. The idea here is to have a faster method of getting the current membrane voltage than recording and getting the whole history.

**Comment by Scaatis** [comment]
@Andrew: I've had a chance to look through the commit now, but it seems to be missing the one part that I could never figure out: The part where a package is being sent from python.

Constructing and sending an SDP packet from Python is a bit confusing, and it doesn't seem to be made easier by the fact that it needs to be done outside of spinnaker.py (I don't think the SpikeSourcePoisson has access to a transceiver?)

**Comment by rowleya** [comment]
Yes, I did the sending outside.  The main thing here though was the restructuring of the poisson parameters region to not have a list of fast sources and a list of slow sources, but just one big list with each source being either fast or slow.  You would need this if you are going to change the rates.  You can do this over SDP, but equally, you could just write the appropriate changes to the region if you are going to be paused anyway.

The SDP rate update code follows:
```
def update_rate(self):
    import decimal
    import struct
    import math
    import time

    rate_val = float(self._rate.get())

    spikes_per_tick = \
        (float(rate_val) * (self._machine_time_step / 1000000.0))
    if spikes_per_tick == 0:
        exp_minus_lamda = 0
    else:
        exp_minus_lamda = math.exp(-1.0 * spikes_per_tick)
    exp_minus_lambda = (decimal.Decimal("{}".format(exp_minus_lamda)) *
                        decimal.Decimal("4294967296"))

    is_fast_source = 1
    if spikes_per_tick <= 0.25:
        is_fast_source = 0

    if rate_val == 0:
        isi_val = 0
    else:
        isi_val = float(1000000.0 /
                        (rate_val * self._machine_time_step))
    isi_val = (decimal.Decimal("{}".format(isi_val)) *
               decimal.Decimal("32768"))

    neuron_id = 0
    while neuron_id < self._n_neurons:
        data = b""
        n_items = 0
        while len(data) < 252 and neuron_id < self._n_neurons:
            data += struct.pack("<IIIi", neuron_id, is_fast_source,
                                exp_minus_lambda, isi_val)
            neuron_id += 1
            n_items += 1
        self._udp_connection.send(struct.pack("<I", n_items) + data)
        time.sleep(0.1)
```

**Comment by Scaatis** [comment]
> you could just write the appropriate changes to the region if you are going to be paused anyway.

Is there currently a supported interface for populations (vertices?) to write back paramaters to SDRAM every time we run and have the SpiNNaker program read it?

**Comment by rowleya** [comment]
No, we haven't done that so far - this would be new code to be written!

**Comment by Scaatis** [comment]
I see. I'll open a new ticket for this then.

This one has rather gone off topic, maybe it should be closed and a new one opened.

Just for the record, I am currently using a workaround where I modified `v_recorder.py` to only return the spikes of the last run, which speeds up the process significantly, though not as much as having a direct read would.

**Comment by alan-stokes** [comment]
id just like to clarify, there is an interface for populations to change their parameters (set, tset, rset etc). But these are currently based in python and do not consider rerun, nor do they consider sdram. But that’s your interface, its just the implementation that needs changing and I've defined how i think you'd need to that in the related issue #181 
Given this, and the fact that youd split the issue over 2 issues now. Im going to close this one.
