### ISSUE TITLE
Use system-installed Python packages

### ISSUE THREAD

**Issue by jougs** [SpiNNakerManchester/sPyNNaker#183]
The [installation instructions](http://spinnakermanchester.github.io/2015.005.Arbitrary/PyNNOnSpinnakerInstall.html) for sPyNNaker start with explaining how to install the required dependencies NumPy, SciPy, Matplotlib, ... from the sources provided by the Linux distribution. This is nice.

To install the SpiNNaker tools, they then use `pip`. However, with the command line provided, `pip` draws in all required packages _again_. This requires bandwidth to download the sources and time to compile everything and creates a parallel installation of basic libraries that I'd rather manage via the package manager of my distribution. Moreover it is prone to errors (see section _Troubleshooting_, which is actually an error during the installation of NumPy).

My suggestion is to change the invocation of `pip` for all SpiNNaker tools from

```
pip install sPyNNaker --user
```

to

```
pip install sPyNNaker --user --no-deps
```

This way, the SpiNNaker tools would use the system-provided versions of NumPy, SciPy, ... and the installation is much faster and more reliable.

**Comment by rowleya** [comment]
Unfortunately, it needs other dependencies that are not installed from the distribution (e.g. SpiNNMan, SpiNNFrontEndCommon etc.).  An alternative then would be just to list each of these, but then we are not getting much use out of pip ;).

The issue with NumPy, SciPy and Matplotlib is that they have C code in them, so pip installing them rarely works.  In theory, the pip command should pick up that they are installed and so not try to reinstall them.  This seems to happen most of the time, but as you are seeing, it does fail on some platforms, and it can fail within a virtualenv as well if the links I have written have actually ended up somewhere else on the system.

Can you tell me what platform you are installing on?  I can see if there is some difference in the install on that platform.  My guess would be that it doesn’t install the metadata for the packages, just the package itself.

**Comment by jougs** [comment]
@rowleya: thanks for the fast reply.

I'm running on Ubuntu 15.04 and managed to install and run everything by adding the `--no-deps` switch and putting all SpiNNaker internal dependencies on the same line as you also suggested. So the problem does not exist anymore for me.

I just wanted to post this as  @alan-stokes told me to report it somewhere. Maybe it would be enough to point this possible solution out in the *Troubleshooting section*?

**Comment by andrewgait** [comment]
Is this still an issue?  I can't see how (as long as you stay within the same (virtual) environment during the entire install) it's possible to first install (say in Ubuntu via apt-get) python-numpy and python-pip, and then when using pip (as @rowleya says above) to install SpiNNaker-related stuff, for it to then try to install things like numpy etc. all over again.  It should be able to pick up that they aren't installed and not try to reinstall them; that's certainly the case in all the environments (Ubuntu 16.04, MacOSX 10.10, and a virtual environment within each of those too) that I've built the toolchain and/or the release version in.

It may be possible to add this to the Troubleshooting section if this actually throws an error, but if the problem is the speed of the install due to bandwidth then I'm not sure whether there's much we can do about it...

**Comment by dkfellows** [comment]
I found that upgrading pip itself so that it could install from wheels made the numpy and scipy installations trouble free in our testing environment. In particular, then you no longer need a compiler to be present (unless you are building new models to run on the SpiNNaker hardware, of course). Perhaps that would be a good thing to add to the instructions? 

It'll definitely be a good idea to have in our introductory material, as that depends on even more compiled modules (to do GUI components).

**Comment by alan-stokes** [comment]
i have vague memories that upgrading pip can be a nightmare, but if we can get line by line instructions on how to do so, then i fully agree.

**Comment by rowleya** [comment]
Easy:
```
pip install --upgrade pip
```

**Comment by dkfellows** [comment]
It also helps to ensure that the `wheel` and `setuptools` packages are up to date. This is the line that I have in our Travis configurations that means that we do very little compilation of anything other than our own code:

```
pip install --upgrade pip setuptools wheel
```

**Comment by rowleya** [comment]
This has now been added to the Python setup instructions
