### ISSUE TITLE
printSpikes doesn't work properly at 0.1ms timestep

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#20]
printSpikes currently prints the time using a format %d - this means that it will round the time to an integer, which is not correct at 0.1ms timesteps.

**Comment by alan-stokes** [comment]
This looks like a issue with the old python way of doing strings, and the offical standard of using .format(). 

Ive updated the code to use the format, and it looks correct (ive added a new intrgrationt test that outputs it and ill be updating it to read the spikes from getSpikes and printSpikes and comparing the output (needs a file interpeter which will be required for from_file_array model anyhow.))

NOTE: ask Alex about from file impl.

I notice that the same issue is for all prints, so im going to fix them all.

will be fixed in capo brnach directly.
