### ISSUE TITLE
Exception("Only rows of up to 255 entries are allowed") thrown in previously working script.

### ISSUE THREAD

**Issue by bvogginger** [SpiNNakerManchester/sPyNNaker#215]
Above exception is thrown in a script of a population-based synfire chain, run on a 48-node board with the latest software version (2016.001 installed via pip).

The script previously worked with a previous software version (status March 2016, installed from github).

Script and error messages are attached in a zip file.
[script_and_error.zip](https://github.com/SpiNNakerManchester/sPyNNaker/files/283680/script_and_error.zip)

**Comment by andrewgait** [comment]
Downloaded script and tested, runs without error against current github master (using sPyNNaker7) with minor alterations.  Could convert to test using sPyNNaker8 if necessary.

**Comment by bvogginger** [comment]
Thanks for checking! No need to convert the script to PyNN0.8. The issue can be closed from my point of view then.

**Comment by alan-stokes** [comment]
2016.001 is not the latest software package now (was the latest when this issue was posted). latest released is 3.0.0. which was released on March 2017. 

recommendation, upgrade to most recent release. If not time critical, wait till October for release 4.0.0, otherwise 3.0.0 may rectify the problem, if 3.0.0 still has the problem wait till 4.0.0. 

we could go test if its in 3.0.0, but given how close we are to 4.0.0, and it being fixed in 4.0.0, id just close the issue on argument its fixed in master.

@andrewgait what ya think?

**Comment by alan-stokes** [comment]
just saw @bvogginger response. fair enough, closing it be, if @andrewgait concurs
