### ISSUE TITLE
spike source array recording scaled-up times!

### ISSUE THREAD

**Issue by iambasab** [SpiNNakerManchester/sPyNNaker#247]
just pasting what I see when I run my simulation:

"2016-09-27 10:51:53 INFO: Setting appID to 30.
2016-09-27 10:51:53 WARNING: A timestep was entered that has forced 
sPyNNaker to automatically slow the simulation down from real time by a 
factor of 10.0. To remove this automatic behaviour, please enter a 
timescaleFactor value in your .spynnaker.cfg
2016-09-27 10:51:53 INFO: Setting time scale factor to 10.0.
2016-09-27 10:51:53 INFO: Setting machine time step to 100.0 micro-seconds."

When I collect spikes from the source in the .dat files, the times in 
milliseconds are all scaled up by a factor of 10; for example, if the 
time of spike was actually at 1500 msec, the .dat file shows this 
recorded at 15000 msec.

**Comment by Christian-B** [comment]
I think this was caused by some confusion of what the timestep value does when passed to setup(..)

It changes how often the code detects if a fire has been fired, not how often a spike is fired.

The default timestep is 0.1 which does cause the "Setting time scale factor to 10.0."  

However the spikes will still fire at the microseconds requested and report in microseconds.

Note: if the spike times are not multiple of the timestep the spiketimes are rounded up.  Ie the spike will only be detected at the next firing of a timestep.
