### ISSUE TITLE
key allocation for population without outgoing edges

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#28]
Currently any system that uses populations which do not output anywhere (sink pops) and the virtual key space have issues when running to dsg. This is becuase DSG asks for the key which is deduced from the routing_infos which do not have anything for it for sink pops. 

Arguablly this is a strnage population, but is realistic in simple simulations and technically allocating it a key would be counter productive. Having some sort of expected value (such as -1) for the dsg when theres no key so that the population on c can know never to spike. Theres no point spiking if your not going anywhere.

decision on our general behaviour in this needs to be decided, but this is my proposal.

Theres the option of using a ground population (raised by sergio) which linsk to all populations that have no outgoing edges and would need to be treat differently during dsg.

any opinions?

**Comment by sergiodavies** [comment]
Although the ground population was a suggestion in the old toolchain to
workaround the problem, I believe this does not solve it: network resources
would still be used to route packets which are not useful for the
simulation.

However, there is the question that if a population does not generate
output in any way, is it at all useful for the simulation?


--

Dr Sergio Davies

Research associate - APT Group   Room IT 302 - IT Building
School of Computer Science       Oxford Road, Manchester
The University of Manchester     M13 9PL, U.K.

mailto: sergio.davies@manchester.ac.uk
mailto: sergio.davies@gmail.com
http://apt.cs.man.ac.uk/people/daviess/

2015-02-04 17:20 GMT+00:00 Alan Stokes <notifications@github.com>:

**Comment by rowleya** [comment]
An unconnected population might be the output population.  You can stll record the spikes...

We could add a boolean send_spike, which if false means that the spike isn't actually generatef.  Note that generating a spike will do no harm though, since it will be dropped immediately.  Another option is to assign a key range that won't be used otherwise and just assign this to every population without a key (e.g. all 1s).

Sent from my android device.

-----Original Message-----

**Comment by AlexRast** [comment]
Are you thinking a population that generates a spike destined for nowhere will 
be dropped because there's no entry in the routing table at the source chip? I 
can't recall what the behaviour of the router is supposed to be if it doesn't 
hit the routing table for a spike originating on it (as opposed to coming off an 
external link) There also is the issue of making sure that the routing table 
generation doesn't create key/mask combinations that the sink neurons match by 
chance - and do get routed out. Just want to make sure these questions have been 
thought through.

As for the use of a sink population, I can think of several modelling situations 
where you'd want "sink" neurons. There are both "debug"-like uses, where you're 
using them to sink spikes for a subnetwork that you want to test in isolation, 
and "real" uses, where e.g. you're using them to model terminal neurons at the 
actuator periphery.

Do the "normal" neuron model types have any sort of flag to indicate they should 
never spike? There is a case for a very simple spike sink that simply swallows 
spikes, but equally for actuator neurons they might plausibly read actual 
membrane potentials and output graded responses to real-world motors. So even 
"ordinary" neuron types might use a "no-spike" flag. Setting a very high 
threshold will probably work most of the time but I would count on that.

**Comment by alan-stokes** [comment]
So just to wrap this topic up. The last conclusion we had on this was to have a bool in the dsg which said "do_spike" which if set to true the next 32 bit word is its key (note this might have to expand in future releases where keys may not be allocated in a continious stream). 

If the send-spike is set to false, then theres some c code within the model to stop it from doing so. Sergio came up with some magic position (to whcih my memory is empty right now) and so hell have to respond to this with it. But this is our current opinion and operating level.

**Comment by alan-stokes** [comment]
done and is already in the capo release
