### ISSUE TITLE
Contributors and licence

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#289]
I think we should have a contributors file to keep tracking of everyone who should be cited as having worked on the toolchain. 

A licence file might also be sensible. This could contain a list of names (duplicating the contributors one) of people who have agreed to the licence. I realize it's GPL v2 (IIRC) but making it explicit might be nice.

**Comment by alan-stokes** [comment]
licence page has been around for years. it can be found here:

http://spinnakermanchester.github.io/common_pages/3.0.0/LicenseAgreement.html

which states our licence is GPL v3 (no idea what the diff is between 2 and 3)

contributors can be found from github insights, and usually is done on a paper by paper basis, as stated in the license agreement page. 

Personally think making a page for this is just going to add workload and be out of date the next time someone commits to the tools, adhoc is likely the best approach here. 

closing issue therefore. welcome to reopen if you think otherwise.

**Comment by Christian-B** [comment]
Would be good to have the standard licence file in each repository pointing to that.

Added to my todo list

**Comment by dkfellows** [comment]
I think that this is important as part of being honest about who worked on the software (in a broad sense) and what the licence is.

Since it is very widely expected that open source projects conform to at least stating the conditions for use, i.e., a licence file, this really has to be a blocker. Listing the contributors isn't a blocker... but the attitude that whoever works on the software will not be credited unless they also work on a paper is quite noxious, and bad for some career paths. 

The contributors list doesn't need to say what each person did or when they did it.

**Comment by Christian-B** [comment]
Done

**Comment by alan-stokes** [comment]
"but the attitude that whoever works on the software will not be credited unless they also work on a paper is quite noxious, and bad for some career paths."
I fully agree, and I've been fighting this attitude for the last 4 years, but alas to no prevail. Glad to have a second supporter in this argument
