### ISSUE TITLE
Generate parameters using a "virtual machine" execution

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#305]
Parameters of neurons could be generated by a program written in "reverse polish notation" generated directly from the user's PyNN commands, and then executed (either on the host or on the machine) to produce the parameters.  This would allow both a simple compact representation, and a relatively simple implementation of population views and assemblies.

As an example, take the following:
```
pop = p.Population(1000, p.IF_curr_exp, {})
pop2 = p.Population(1000, p.IF_curr_exp, {})
pop[0:100].set("cm", 0.5)
a = p.Assembly((pop[50:150], pop2[50: 150]))
a.initialize_v(-65.0)
```

With 100 neurons on a core, this might be represented as a matching program on the second core of the first population as:
```
# set up the initial population with default parameters
# (truncated to cm and v_init)
100 199 0.25 -70.0 create_neuron

# set the 0th parameter (cm) to 0.5 for neurons 0 to 99 
# (ignored here but done for ease)
0 99 0 0.5 set_param

# initialize the second parameter (v) to -65.0 for neurons 50 to 149 
# (only 100-149 done here but again done for ease)
50 149 1 -65.0 set_param
```

Population views and assemblies would add to the program as the user calls methods on them.

**Comment by alan-stokes** [comment]
i was thinking about this a little bit over the easter weekend (god forbid i work over the hols) and a thought occurred. If you have a random distribution which is intermingled with sets. aka below:

pop = pop(100)
pop.set(x, 20)
pop.set(x, random_dist(0, 100))
pop_view = popview(pop, every 10)
pop_view.set(x, 30)

wont you have to explode the random dist (or at least run it over all the atoms) before executing the other changes, as otherwise your sample of the random number distribution will be off? 

therefore you're got a set of commands, all of which end up running on pop based atoms...... which means on chip is really really problematic, whereas on host might be as slow / memory based as holding the results in the end?

just a thought.

**Comment by andrewgait** [comment]
This is a nice idea which requires further consideration in the future.  I think it might work relatively well with the delay / weight / synapse / matrix generation that is now done on chip... ?

**Comment by dkfellows** [comment]
While using (a cut-down) Forth to do data generation on chip is not a _bad_ idea, I can bet that the idea would be seen as very hostile to just about anyone actually developing a new model! Not happening...
