### ISSUE TITLE
energy estimate for a model running on spinnaker

### ISSUE THREAD

**Issue by iambasab** [SpiNNakerManchester/sPyNNaker#318]
Is it possible to estimate the power consumption of a neural circuit model running on the machine?

**Comment by dkfellows** [comment]
Needs:
- [ ] Energy estimator for CPU loading.
- [ ] Energy estimator for messages.

Talking to Luis, we believe that we can estimate the power cost of FPGA links as constant (i.e., linear energy use over time) due to the need to keep off-board links synchronised, and the cost of on-board and on-chip communications can probably be obtained from published papers.

CPU load estimator will require code. See `update_load` in `scamp-3.c` for outline of how to get loading (read from `sc[SC_SLEEP]`; `sc` and `SC_SLEEP` defined in `spinnaker.h`), but needs better sampling strategy. I think we need a high frequency timer, some sort of random offset (uniform distribution, by busy loop) to spread the samples over the clock period, and to only collect aggregate data. The need for aggregate only is because we don't need exact detail of when things were sleeping, and a high-resolution timer with high-resolution data will fill DTCM very rapidly indeed.

**Comment by dkfellows** [comment]
[Work in progress](https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/tree/chip-power-monitor)…

**Comment by alan-stokes** [comment]
[still in progress ... ](https://github.com/SpiNNakerManchester/PACMAN/tree/chip-power-monitor)
[still in progress ... ](https://github.com/SpiNNakerManchester/sPyNNaker/tree/chip-power-monitor)
[still in progress ... ](https://github.com/SpiNNakerManchester/PACMAN/tree/chip-power-monitor)

**Comment by alan-stokes** [comment]
[added still in process ...](https://github.com/SpiNNakerManchester/SpiNNMachine/tree/chip-power-monitor)
 is up to point of testing against real energy measaurements. using microcircuit as benchmark

**Comment by alan-stokes** [comment]
pull requests for when testing is finished:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/155
https://github.com/SpiNNakerManchester/PACMAN/pull/98
https://github.com/SpiNNakerManchester/sPyNNaker/pull/341
https://github.com/SpiNNakerManchester/SpiNNMachine/pull/42
https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/51

**Comment by alan-stokes** [comment]
[added still in process](https://github.com/SpiNNakerManchester/SpiNNMan/tree/chip-power-monitor)

**Comment by alan-stokes** [comment]
pull requests for when testing is finished:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/155
https://github.com/SpiNNakerManchester/PACMAN/pull/98
https://github.com/SpiNNakerManchester/sPyNNaker/pull/341
https://github.com/SpiNNakerManchester/SpiNNMachine/pull/42
https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/51
https://github.com/SpiNNakerManchester/SpiNNMan/pull/83

**Comment by alan-stokes** [comment]
includes turning off boards between detection and loading (mapping, dsg phase)

**Comment by alan-stokes** [comment]
having ran this comparing between hard energy measurement and estimate, the estimate is out by a factor of 2 overall. but factor of magnitude out in areas. more investigations required

**Comment by alan-stokes** [comment]
so this work is now in master. Mainly as it solves a few other issues and was easier to merge the whole thing than cherry pick. 

The report can be found by turning on 

[Reports]
reports_enabled = True
write_energy_report = True

in your cfg file. If you want to even more energy conscious, you can turn on the functionality for turning off the machine between discovery and loading. This is also done by the cfg file. params below:

[EnergySavings]
turn_off_board_after_discovery = True

There are two reports. 1 is a detailed covering each core energy usage and other gubbins. 
                                    2. is a summary report which results in total Kwh etc.
Its worth noting that as of master now. The report is approx 100 Wh off from running a 100% column on a rack with cooling etc. More work will be spent to refine these estimates at some point, but at least now it'll give you a ball park figure if you want one.

**Comment by alan-stokes** [comment]
closing as last release had such functionality
