### ISSUE TITLE
PACMAN is currently Neural Specific in the area of Key Allocation

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#33]
Key Allocation in PACMAN assumes that it must be dealing with vertices with atoms (but key allocation should only work on a partitioned graph, which might not have the concept of atoms).

This is particularly obvious in the _generate_keys_with_atom_id functions, which is then highlighted by the SubedgeRoutingInfo, which now contains a key_with_atom_ids_function.

This must be re-thought!

**Comment by alan-stokes** [comment]
to keep this comment up to date. 

Rowley and myself have come to a logic of number_of_keys required constraitn and he has spent the week rewiring the code to take into account this new operational state. This is to decouple the 1-1 mapping between neuron/atom and key, which is liekly to be requried for p2p2 and possible others. The key allocator is also being adjusted to reflect these changes.

On top of these, Rowley is travelling down the togic behind the key_with_atom_ids_function so that in future we can use arbitary masks to help with routing table entries and other resources in future (say 1m core machine). There is some level of limitations here and is currently being semi benched so that when we come back to the issue,w e know what to do.

**Comment by AlexRast** [comment]
Should this "number of keys required" or "address space" constraint maybe be in 
powers of 2? That would *greatly* simplify the job from the POV of key 
allocation, even if yes, there's a chance you could lose close to 1/2 the 
mappable key space if the constraints are particularly awkward.

**Comment by rowleya** [comment]
The number of keys required is given to the algorithm, but it is then up to the algorithm to do with it what it wants.  In our case, it does indeed round this up to the nearest power of 2 if it isn’t already.

**Comment by alan-stokes** [comment]
done via the new malloc key allocator. Already resides in the capocaccia branch. there is no longer any PyNN key allocator
