### ISSUE TITLE
Create provenance data interface for individual cores

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#35]
At present, there is no means for run time provenance data to be retrieved and reported on from individual cores.  We should provide a class for the data such as:

class ProvanenceData(object):
    def __init__(item_name, item_value)

and then an abstract class for this such as:
class AbstractProvidesProvanenceData(object):
    
    @abstractmethod
    def get_provanence_data_items(self):
       pass

get_provanence_data_items can then return an iterable of ProvenanceData.

**Comment by alan-stokes** [comment]
I would wait till after front end common has been merged. but the functionality def needs to be in. esp for buffered in stuff. but we could use it for soooo many other things, such as how long and how much behind core where during execution

**Comment by alan-stokes** [comment]
So ive added a interface into front end common which is called AbstractProvidesProanenceData which takes msot of what was described above, but instead of get_provanence_items as described above, i felt it was better to force the object using this to be restricted to one file to write proanence data into.

So it suppies _write_provanence_data_in_xml(file_path) which allows the object in question to write all its data into this file. 

This i feel is more controlled (though only slightly) than using a retun of iterables of provanence data which could be in any format and thus more difficult to interprete in the front end.

Ive also added a front_end_common_provanence_functions which allows a front end to extract data from the machine (currently only does routing diagnostics) as making the machine/chip/router felt ......clunky. The spinnMachine object is really imutable and thus cant really be expected to provide the ability to get data from the real machine. SpinnMan is just a interface and shouldnt be forced to udnerstand what a machiens provanence is, thus i landed on the front end.

This has been committed, but as its a very little change, i feel its not too great a task to modify. Im going to close this issue, with the pervado that anyone's feelings cna open it bakc up.
