### ISSUE TITLE
spike_processing.c -- No writeback of plastic-plastic region into SDRAM if queue is full

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#408]
In _setup_synaptic_dma_write( ) ...

```c
    // Start transfer
    spin1_dma_transfer(
        DMA_TAG_WRITE_PLASTIC_REGION, buffer->sdram_writeback_address + 1,
        synapse_row_plastic_region(buffer->row),
        DMA_WRITE, n_plastic_region_bytes);

```
```spin1_dma_transfer``` will return -1 if there is not enough space in DMA queue. There exists no check here to ensure the writeback happens.

**Comment by rowleya** [comment]
There *should* be no circumstances in our code under which this happens (we don't do enough DMAs for this to occur as far as I know), but adding it would be a good idea...

Note that spin1_dma_transfer will return *0* if there is not enough space in the queue.  Otherwise, it returns the id of the transfer.  Are you sure you aren't filling up the queue by checking for -1 in other code?

**Comment by pabogdan** [comment]
@rowleya you are correct, I was checking against an incorrect value.

**Comment by rowleya** [comment]
It may still be worth adding this check to our code as well since other parts may get more complex in the future...

**Comment by andrewgait** [comment]
As far as I can tell, I think this has been dealt with in the recent structural plasticity / STDP work.

**Comment by andrewgait** [comment]
Closing issue, but please reopen if necessary.
