### ISSUE TITLE
Spike source poisson drifts

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#43]
With long enough runs, the poisson source average rate drifts downwards, particularly at 1ms timesteps.  This is due to timestep granularity and can be fixed with an accumulator of fractional timesteps.

**Comment by hopper333** [comment]
Hi Andrew

Is this related to what we were talking about a long time ago?

Let me know if you want any input.

M

On Apr 2, 2015, at 4:20 AM, Andrew Rowley wrote:


With long enough runs, the poisson source average rate drifts downwards, particularly at 1ms timesteps. This is due to timestep granularity and can be fixed with an accumulator of fractional timesteps.

**Comment by rowleya** [comment]
Yes, this is the one – I think it is easy enough, although I don’t know if I will personally have time to fix it.

**Comment by alan-stokes** [comment]
Just want to check if this has been done or not. So I'm moving it to sept milestone as its likely not to be fixable before capo now.

**Comment by andrewgait** [comment]
Interesting to read this old issue - just to say that I don't think I've seen anything like this on the longer runs I've been doing recently (PR to follow in the near future).  Perhaps it's no longer an issue?

**Comment by rowleya** [comment]
I think this was fixed some time ago... I will close this for now.
