### ISSUE TITLE
speed-up FromListConnector

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/sPyNNaker#437]
When the lists are large searching for incomming connections takes a long time because we're searching the entire list every time [(line 220)](https://github.com/SpiNNakerManchester/sPyNNaker/blob/63f73083d81febad18bdc08a8db09fab5144e3ef/spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py#L220)

Would it be safe to delete the items we already found in the list after parsing them to the synaptic block? This would reduce the search space every time a vertex slice is processed, thus reducing the time to process it.

**Comment by alan-stokes** [comment]
issue is youd need to clone the connection list before you could do anything. The end user gave you that object, changing it would be a breach of api (just imagine a 2 run phase where the end user uses the same list in a new projection and then wonders why its empty). The cloning would take a while, but after that you could. Youd need to measure to see how it performs. and just ebcuase we asked once, does not mean we wont ask again, the partitioner is a tril and error process.

**Comment by rowleya** [comment]
I think that we clone the list into a numpy array anyway to make the whole thing faster.  If the connections are then removed from this list at the point when the synaptic block was generated, that should be faster, although as Alan points out, there isn't anything in there that says it only has to be done once...

Other solutions would be to look at why the numpy array is so slow in the first place, which I think is due to multiple filterings of the list.  I would guess that there are solutions that involve writing some C code that more directly accesses and filters the numpy array directly.

**Comment by andrewgait** [comment]
Looking at this code a bit more, it seems to me as though there's a lot of repetition and duplication that could be unnecessary - I may be wrong, but I think it should only be necessary to set the `mask` variable once per block - currently it is set in every function where it is required, which seems like overkill to me.  In other connectors the equivalent function is first set to None, then updated by the first function that calls it, and then after that in this instance no further update of it would be necessary and any other function requiring the mask could just simply ask for it.

**Comment by andrewgait** [comment]
The PR at https://github.com/SpiNNakerManchester/sPyNNaker/pull/632 is related to this - I'd say this issue can probably be closed once that branch is merged.

**Comment by andrewgait** [comment]
PR #632 has been merged so closing this issue.
