### ISSUE TITLE
setuptools makes git install tricky

### ISSUE THREAD

**Issue by neworderofjamie** [SpiNNakerManchester/sPyNNaker#52]
If you install from git by checking out all the modules and attempting to install each with some variant of python setup.py develop it makes a fairly good job of trashing your virtualenv/site-packages by trying to download the modules from pip. I think this is something to do with versions and can be worked around by doing python setup.py develop --no-dep, but is there a better way?

**Comment by rowleya** [comment]
I am surprised that this doesn't just work - it may depend on the order that you do this in, although the end result should be the same.  This is because I would expect that while each setup.py develop will install any dependencies, any future setup.py develop of one of those dependencies should override the site-packages installed version (this version will still exist but it shouldn't be used).  Note though that you still need things like numpy in your virtual-env (the virtual-env install instructions with symlinking should work here).

The order recommended would be:
SpiNNMachine
SpiNNMan
PACMAN
DataSpecification
SpiNNFrontEndCommon
sPyNNaker
sPyNNakerExternalDevicesPlugin

Note that you only need ones you are altering in develop mode as well; the pre-release versions of the others should be fine. In this case, follow the order above but only for those that you are going to change.

**Comment by neworderofjamie** [comment]
Yeah, it seems to work if you do it in that order - Could that be documented somewhere as without that it's somewhat tricky to use the version checked out of our public github :)

**Comment by alan-stokes** [comment]
done. is now in the instlalation wiki page under github installation. I think i got it right. please can one of you two check.

**Comment by neworderofjamie** [comment]
Fixed a typo in the command line argument, tweaked the wording and made the
IN ORDER bold :)

**Comment by alan-stokes** [comment]
thanks jamie
