### ISSUE TITLE
Visualiser is broken

### ISSUE THREAD

**Issue by qian-liu** [SpiNNakerManchester/sPyNNaker#55]
Opened database successfully
Reading pop_1
*** Error in `./vis': free(): invalid pointer: 0x00000000016f8b18 ***
Aborted (core dumped)

**Comment by alan-stokes** [comment]
having done a bunch of checks and tests, the vis now works in linux (ive had to comemnt out the free() code in the database reader (as this was what was causing issues, and i couldnt figure why it was failing)) Im deducing windows vs linux bugs again. 

Ive also modified the tag data writer in python to use the index of the vertex, not a arbitary one. 

Also modifed the spikeio so that it works with the c vis as well as the python behaviour.

thus, closing issue (will be merged into capo branch when the augmented tests brnahces move in).
