### ISSUE TITLE
from file test seems to not behave as expected

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#57]
Hi alex, 

Ive rejiggled your "from list type intergration tests" so that they are automatic and use past runs to verify if things are working. Now ive  split up the tests and rejiggled them so that they are unittests and follow pep8 complience. 

Please look into spynnaker brnach  augmented_tests for this work

Now the "from_file_connector_tests" has been cleaned up and has its spikes recorded during one execution, and then its ran a second time and the spikes are compared again, unfortantely, the spikes never meet up twice ina  row. Ive looked at the random generators, and they are seeded. So this is beyond me. Please can you fix this test set for me,

regards
Alan

**Comment by alan-stokes** [comment]
Hi Alex, did this ever come to a completion?

**Comment by alan-stokes** [comment]
due to both myself and alex not being able to figure out what the feck this tst does, it is to be deleted and removed. issue closed.

**Comment by AlexRast** [comment]
A misunderstanding between Alan and myself on who knows what. I know what the 
internals of the script are supposed to do, I just am not familiar with the 
enclosing framework that it's now been wrapped in (made as a funcion of a 
class). I think this should be reopened because I'm in a position to run the 
test as soon as I get some advice on what the expected test harness is supposed 
to be.
