### ISSUE TITLE
Delay Extension total_n_vertices based backoff causing overflows in big  network.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#583]
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
line:288 insertes a delay based on the total number of neurons

This delay while random here causes a CONSTANT delay in 
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker/pyNN/models/utility_models/delay_extension_vertex.py line 295

On too high a number this causes a timeroverflow every single tick from which the neuron NEVER recovers and eventually hangs.

Found and simulated by ramming up
https://github.com/SpiNNakerManchester/IntroLab/blob/master/synfire/synfire.py
n_neurons = 100
n_populations = 2000 
weights = 0.5
delays = 17.0
simtime = 1000

**Comment by Christian-B** [comment]
I checked that the the delay was 100% the issue by running the script in the original 20 n_popluations but simulating the effects of a large number of verticies by 

        spec.write_value(6000 + random.randint(0, total_n_vertices))

**Comment by Christian-B** [comment]
This  raises a number of questions.

1. Does the delay really need to be base on the total number of vertices in the WHOLE network?

2. Why is there a delay called before even check for spikes. This causes the delay even when there are NO spikes.

**Comment by alan-stokes** [comment]
for 

2. its a off set spreading to try to reduce the peak spikes on the network. Otherwise you can get back pressure or dropped packets.

1. yes and no. you need it, and you need to try to ensure the cores of the network are not synced (thus producing a higher peak) but you could instead have a TDMA or even simpler, we could just say a max offset (say 1/2 the timer tick) and then just iterate adding 1 us to each new vertex seen, and then cycling. this would also give us more determinism than using a random. we could also allow it to be adjustable by the normal routes. cfg and param. It'll be likely as balanced as a random, possibly better so.....

**Comment by rowleya** [comment]
I believe this is fixed in #539.  The random delay is now incorporated in to the "phase" parameter when setting up the timer tick.  This may or may not be ideal however and having a cap on the maximum phase might be a good addition to this PR; without this, binaries may end up more than half a timer-tick out of phase (maybe even a whole timer tick).

**Comment by rowleya** [comment]
I have implemented the above idea now - the maximum offset is 10% of whatever length a timer tick is in microseconds (taking the timescale factor into account).  The offsets are also now not random, but instead a fixed value for each subvertex of a vertex based on the maximum; this means that with enough vertices you will get overlap, but that would be true with any limit!

**Comment by rowleya** [comment]
Not currently configurable.  As this now works as a phase it means that this will not cause the cores to overrun timer ticks.  At most each core is 10% out of phase with other cores e.g. at 1ms timer ticks core A starts a timer tick then core B might start up to 0.1ms later, but still has 1ms to do its work before the next tick starts.  Therefore I don't see it needs to be configurable...

**Comment by andrewgait** [comment]
Fix for this was merged, so closing.
