### ISSUE TITLE
FixedProbabilityConnector sometimes overflow

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#587]
found with 
https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/unittests/model_tests/test_connectors.py
 
in rare but not zero case the asserts 
            assert max(source_histogram) <= max_row_length
            assert max(target_histogram) <= max_col_length
Fail.

Passing a constant seed into FixedProbabilityConnector is NOT a FIX!

We need to decide between
1. have an actual max 
2. Capping to the utility_calls.get_probable_maximum_selected value
3.Capping to the higher of utility_calls.get_probable_maximum_selected or some user specified value.
a. in a config
b. as an extra parameter to the connector

Could be related to:
https://github.com/SpiNNakerManchester/sPyNNaker/issues/585

**Comment by Christian-B** [comment]
I did a check and max_col_length and max_row_length do come out with the same value every time for each connector settup.

**Comment by andrewgait** [comment]
The issue here is that connector.create_synaptic_block(..) will be called with a MockSimulator, but won't be called in usual usage for on-machine connectors such as the FixedProbabilityConnector (this will also be the case for FixedNumberPre and FixedNumberPost connectors once their PR is accepted).  We could update connector.create_synaptic_block() to better match the connector.get_n_connections functions, but a better solution may just be to move these tests out into integration tests (indeed, there are probably already integration tests for these connectors anyway...).

**Comment by rowleya** [comment]
The synaptic expander never generates a block too big.  I think that the code in pop_based_master_pop_table also has this property in the Python code, although I am not sure that it is guaranteed to always be smaller (that could do with a test in itself).  If both of those eventually restrict the row size, even artificially, this test won't be that important...

**Comment by Christian-B** [comment]
tests are failing/skipping this way.

**Comment by andrewgait** [comment]
Oops.  Looks like I just fixed this for the FixedProbabilityConnector and not the FixedNumberPostConnector - not sure whether this was broken at that time as well, but it is right now.
