### ISSUE TITLE
pop.initialize( silently does nothing.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#600]
Related to:
https://github.com/SpiNNakerManchester/sPyNNaker/issues/599

Email with @apdavison 
I would expect it to raise an Exception, as pop.initialize() should only be called at the start of a simulation, or after sim.reset().

**Comment by andrewgait** [comment]
Making notes on this: currently pop.initialize(...) does "work" in between two runs as long as no pop.set(...) is also called (there must be some form of overwriting going on here that takes the current state off the machine when set() is called).  

This should most likely be changed so that the current state overrides any call to initialize(), and on top of that there should at least be a warning thrown (and perhaps an exception) if the user tries to initialize() anything in between two runs without having called reset() first.

**Comment by andrewgait** [comment]
This was fixed by https://github.com/SpiNNakerManchester/sPyNNaker/pull/669, so closing.
