### ISSUE TITLE
“v” is not a valid parameter for IF_curr_exp.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#601]
related to 
https://github.com/SpiNNakerManchester/sPyNNaker/issues/599

email with @apdavison 
in reply to:
sim.setup(1.0)
pop = sim.Population(1, sim.IF_curr_exp(v=-64, tau_syn_E=1), {}, label="pop")
He said:
"The script shouldn’t even get that far, though, as “v” is not a valid parameter for IF_curr_exp."

Alternatives are:
1. Allow the v but log a non standard warning
2. Move v to additional parameters
3. A combination of 1 and 2

I assume the same applies to other state variables.

**Comment by apdavison** [comment]
For reference, this should look like:
`pop = sim.Population(1, sim.IF_curr_exp(tau_syn_E=1), initial_values={'v': -64}, label="pop")`

**Comment by andrewgait** [comment]
Just to add a note: what @apdavison suggests here works already as far as I can tell; it should be possible to at least direct users to do things this way rather than the other less correct way.  As someone commented on a different issue, this could simply be a SpiNNaker "feature" if we wanted it to be...

**Comment by Christian-B** [comment]
I agree as long as the "offical" way works there is no reason to break other ways.
A log once warning is suitable.

**Comment by Christian-B** [comment]
fixed with https://github.com/SpiNNakerManchester/sPyNNaker/pull/671
