### ISSUE TITLE
offset causing spikes to arrive too early.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#619]
Script:
import spynnaker8 as sim

sim.setup(timestep=1.0)
sim.set_number_of_neurons_per_core(sim.IF_curr_exp, 1)

input = sim.Population(
    1, sim.SpikeSourceArray(spike_times=[0]), label="input")
pop_1 = sim.Population(2, sim.IF_curr_exp(), label="pop_1")
sim.Projection(input, pop_1, sim.AllToAllConnector(),
               synapse_type=sim.StaticSynapse(weight=5, delay=1))
pop_1.record(["spikes", "v", "gsyn_exc"])
sim.run(3)
print(pop_1.spinnaker_get_data("v"))
sim.end()

notice how the voltage is different for the two cores.

We noticed that setting timer_offset to zero stops this but at a probable cost of too many spikes hitting at the same time.

questions.
1. Is this acceptable?

2. Do we want to make it so it can be turned off but at with a known risk of spike clashes.

3. Why is it just appearing now?

4. Do we care that different runs have different neurons firing differently.

**Comment by rowleya** [comment]
This is related to SpiNNakerManchester/SpiNNFrontEndCommon#407.

If the placement is exactly the same I would, for a simple script in any case, expect that the results were the same.  However if the placement is different, this results in different offset times, which means different cores might be in different time steps at any instance.  If a spike is received in the "wrong" time step, meaning it was sent in one time step from the sender perspective, but a different time step from the receiver perspective, this can give different results.  

This should be understood by designers of neural networks, and the networks should be set up to cope with this.  Structures such as balanced random networks cope with this in general, but this effect will still result in a different number of spikes at different times.

There is a bug at present, but the bug is that the tools are not doing the same thing each time they are run, due to the use of unordered data structures.  This should be resolved.

**Comment by andrewgait** [comment]
I think this is something that has broken recently.  https://github.com/SpiNNakerManchester/sPyNNaker8/blob/a265ad2e9f733f6677f3afcdcc1fd6fe5c7e75d8/p8_integration_tests/test_population_with_multiple_connectors/test_population_with_multiple_connectors.py (which is a slightly more complicated version of the script posted above) is no longer giving the same answer as it used to - now neuron 0 spikes at time=2 and neuron 1 spikes at time=1, whereas they both previously spiked at time=2.  It's related to partitioning and placement but I think there's something wrong with a delay value somewhere...

**Comment by rowleya** [comment]
I don't think this is a delay issue, though if you can check that, it would be good!  I believe that it is down to simple offsets between the populations that used to be random, and so it was more likely that the populations were offset to after the spike source array went off.

**Comment by andrewgait** [comment]
The problem here too is that the script behaves differently after you force the population to be partitioned - if you take the set_number_of_neurons_per_core(..) call out, then it does what you would expect it to (i.e. both neurons have the same voltage trace).

**Comment by andrewgait** [comment]
Having had a look at this a bit further, the behaviour is perhaps more worrying when using set_number_of_neurons_per_core(..), particularly with low values.  If you increase the population size in the above script but keep set_number_of_neurons_per_core(model_name, 1), what should happen?  What actually appears to happen is that the majority of the neurons will fire at time=1, but a few will fire at time=2.  (If the offsets used to be random but aren't any more then this is perhaps more confusing...)

**Comment by rowleya** [comment]
So inside the current master code, each vertex has a timer_offset to ensure that they don't send spikes at the same time.  This is implemented in the C code through an offset in the timer; the first timer tick is extended by this amount. So if the timer is set to 1000us (the normal for 1ms time steps), and a vertex has a timer offset of 100, the first timer tick will go off after 1100us, with subsequent ticks being at 1000us intervals after this.

The vertices in Python then have to provide a value for this offset.  This is done with a maximum value of 10% of the total time available for a time step; there will be some repeats when the number of subvertices is high (since you can't divide 100 by more than 100 and still get an integer).

Having written the above, I now understand what is happening now that wasn't happening before when we were using randomly generated offsets.  It isn't to do with the offset, but is how it is implemented.  In the previous version, we were using the same timer tick on each core, but then using a busy-wait to implement the delay.  In the current version, we extend the first timer tick.  The difference then is that when the first timer tick is extended, the cores will be on different time steps at the same time, but with a busy wait, cores on the same board are likely to be on the same time step at the same time.

Which is correct is open to debate; arguably using a busy wait is wasteful, and mean each core has a different number of clock cycles available to perform the neuron processing.  That said, spikes received while the busy-wait is ongoing will still be processed, so it is only wasteful when there are no spikes to process.

Possible solutions:
 1. Go back to a busy wait.
 1. Accept the consequences of not using busy wait.  Note that longer simulations (> ~2-3 seconds) on multiple boards will probably exhibit this behaviour since board clocks tend to drift.
 1. Wait for Dave's assembly code implementation where spike processing is done around the neural updates, and then make it possible to process a variable number of spikes before any neural processing is done, avoiding a busy wait (downside is there may be no spikes to process, or the same number of each core).
 1. Wait for the split-core model where synapses are done on a different core, and then synchronise the synapse cores but delay the neuron cores.  Since the neuron core is the bit where this is important, this should work reasonably well (though there may be unforeseen issues).

**Comment by rowleya** [comment]
Note: it might be interesting to create a network that runs on multiple boards for say 10 seconds, and see if this eventually becomes de-synchronised.  If so, this might mean that by moving back to using busy wait we are just delaying the problem until people have larger networks.

**Comment by andrewgait** [comment]
Is this related to any of the recent work to deal with boards / jobs with drifting issues?  I'm inclined to tag this for a future release anyway.

**Comment by andrewgait** [comment]
I wonder whether there might be some mileage in seeing whether the choice of using 10% of the total time step could be played around with a bit.  Certainly the associated issue we looked at today benefited from reducing this value, but I appreciate there’s probably a balance that needs to be struck somewhere.

**Comment by rowleya** [comment]
One option, which could be tricky to implement, would be to ensure that sources have an offset smaller than neuron cores.  This would make sure that the source spikes before any core receives it.  This might still have issues though if the targets are now split up differently and communicate with each other.

**Comment by andrewgait** [comment]
Reading back through these issues, the discussion seems relevant to the recent problems with the vogels_2011 script (particularly the non-STDP section).  Are the changes made to deal with that on their own branch or part of the bitfield project?

**Comment by alan-stokes** [comment]
they live on their own branches. there is even a pr
https://github.com/SpiNNakerManchester/sPyNNaker/pull/819

BUT THIS is still a draft. and is covering quite a few fiddles to try to get it to work. ive been messing with it last week and it still wont scale properly with time scale factor. so i have yet to get it to be able to handle making a call slower by logging stuff.

**Comment by Christian-B** [comment]
Test script no longer has the described behaviour.

Closing this as I think no longer relevant.
