### ISSUE TITLE
SpikeSourcePoissonVariable not behaving correctly

### ISSUE THREAD

**Issue by ej159** [SpiNNakerManchester/sPyNNaker#757]
It appears that the SpikeSourceVariable is using random rates and not those passed to it. The script below exemplifies this. The output spikes should resemble the input rates when plotted.

```python 
import pyNN.spiNNaker as sim
from keras.datasets import mnist
import matplotlib.pyplot as plt
from spynnaker8.extra_models import SpikeSourcePoissonVariable
import numpy as np

# Grab some data for rates
(x_train, y_train), (x_test, y_test) = mnist.load_data()
rates = x_test[0,:]

# Scale rates
rates = np.ravel(1000*rates/255)

# Plot rates
plt.imshow(rates.reshape((28,28)))
plt.show()

# Set up SpikeSourceVariable
sim.setup()
pop = sim.Population(784, SpikeSourcePoissonVariable(rates=rates, starts=[0]*784,durations=[1000]*784))
pop.record('spikes')
sim.run(100)

#Process output spikes
output = np.int_(pop.spinnaker_get_data('spikes'))
sim.end()
output = np.bincount(output[:,0], minlength=784)

#Plot output spikes
plt.imshow(output.reshape((28,28))) # This should be similar to the input rate plot
plt.show()
```

**Comment by rowleya** [comment]
The problem is that the ```rates``` array is a one-dimensional array of 784 items, which is telling the code that there are 784 rate values *for every neuron* rather than a rate for each neuron.  This is because the variable rate source expects a list of rates per neuron, so if you want to specify a different list of rates for each neuron, you need a list of lists!

Slightly easier to understand is if you replace the population with this:
```
pop = sim.Population(784, SpikeSourcePoissonVariable(rates=rates.reshape((784, -1)), starts=[[0]]*784, durations=[[1000]] * 784))
```

In this, each neuron is given a list of size 1 for each of the rates, starts, and durations parameters.  If you really do want a single value for each neuron that doesn't change in the simulation, a better option is of course the regular ```SpikeSourcePoisson```, which then accepts the lists as you have them, but I am guessing this is just a minimum example and that you have something else in mind...

Note that what you specified isn't an error, it just isn't what you thought you said!

**Comment by alan-stokes** [comment]
having installed teras and tensorflow. This test does indeed show up something. I found
