### ISSUE TITLE
Ill defined behaviour when reducing number of connections in a row

### ISSUE THREAD

**Issue by pabogdan** [SpiNNakerManchester/sPyNNaker#759]
I've just noticed some interesting behaviour when trying to run an experiment with structural plasticity. I had a bug in my script and I was trying to create synaptic rows of length `258` so this bit of code (@L450-453 in synapse_dynamics_stdp.py  )
```
        # Reduce until correct
        while (self.get_n_words_for_plastic_connections(n_connections) >
               n_words):
            n_connections -= 1
```
would trigger to attempt to reduce the number of connections to under 256 because of L55-67 in synapse_io_row_based.py:
```
        try:
            return population_table.get_allowed_row_length(size)
        except SynapseRowTooBigException as e:
            max_synapses = dynamics.get_max_synapses(e.max_size)
            raise_from(SynapseRowTooBigException(
                max_synapses,
                "The connection between {} and {} has more synapses ({}) than"
                " can currently be supported on this implementation of PyNN"
                " ({} for this connection type)."
                " Please reduce the size of the target population, or reduce"
                " the number of neurons per core.".format(
                    in_edge.pre_vertex, in_edge.post_vertex, row_length,
                    max_synapses)), e)
```

However, my connections are structurally plastic so the length of the row gets padded to the set value (258) regardless of `n_connections`, leading to an underflow on `n_connections`. 

My question: what is the use of reducing the n_connections in a row if we throw an exception immediately after exiting this function?

**Comment by andrewgait** [comment]
@rowleya may be in a better position to answer this question; but I'm confused as to how you are expecting a synaptic row of length 258 to work (I assume on a single core?), as I thought there was a hard limit on this of 255 (master_pop_table_as_binary_search.py L162-170).  The point of the reduction is to get the word alignment correct so that the numbers reported in exception that then gets raised are accurate, not so that the value that comes out afterwards can be used for anything.  I think.

**Comment by rowleya** [comment]
It is impossible for the current implementation of the master population table to function with rows of more than 255 words + 3 header words.  When using STDP, 255 words might not be the same as 255 synapses since you might be using more than one word per synapse.  The STDP max_synapses code tells you the maximum number of connections possible for the given number of words; it doesn't reduce the stored number of connections though, only the number of connections returned from the function.  The function is described in more detail here:
https://github.com/SpiNNakerManchester/sPyNNaker/blob/3a629a1d99888bc940771fbdc61ae95745e09545/spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py#L71-L77

**Comment by pabogdan** [comment]
To reiterate, I didn't meant to have 258 connections, but I didn't get any error out because of the reduction to "the correct size". In the while loop I linked `n_connections` starts off at 258 then decrements to 0 then underflows. This shouldn't happen!

**Comment by rowleya** [comment]
I assume that somewhere there is a call to that function that you think is not working; the function is self-contained in that it shouldn't actually reduce n_connections anywhere but in a return of value.  Do you know where it is being called from where it results in this decrement to 0?

**Comment by pabogdan** [comment]
L55-67 in synapse_io_row_based.py, more precisely the `dynamics.get_max_synapses(e.max_size)`
```
        try:
            return population_table.get_allowed_row_length(size)
        except SynapseRowTooBigException as e:
            max_synapses = dynamics.get_max_synapses(e.max_size)
```

**Comment by andrewgait** [comment]
I think what's happening here is that there's no safety check when size=0 on L56, which I think is possible - this function is called on two separate occasions when using self._get_max_row_length from synapse_io_row_based.py L107-112, for undelayed and delayed synapses; I'm guessing in your example that you either have no delays that require delay extensions, or that all your delays require delay extensions?  It's probably just a simple case of putting a safety check for delayed_n_words > 0 and undelayed_n_words > 0 around L107-112 (as indeed happens further on for (un)delayed_max_n_words), I think.
