### ISSUE TITLE
Synaptic amplitude proportional to time step in IFCurrDelta model 

### ISSUE THREAD

**Issue by apdavison** [SpiNNakerManchester/sPyNNaker#762]
With the `IFCurrDelta`/`IFCurDelta` model, a synaptic event with a weight of 5.0 produces a change in membrane potential of 5.0 mV when the time step is 1.0 ms, a change of 0.5 mV when the time step is 0.1 ms, etc.

This seems to me to be undesirable. The same weight should always produce the same ΔV (within the limits of solver error) irrespective of the details of the numerical solver.

**Comment by rowleya** [comment]
What is the units of the weight for IFCurrDelta?  

If it is in mV, this is the issue we have always had with it, as we currently assume nA.  

If the weight *is* in nA, then applying the weight at 0.1ms would have a different effect than at 1.0ms given the Delta says to apply the weight for a single time-step.

**Comment by apdavison** [comment]
I'm not sure what units are intended, but I would argue for mV, since a delta function has infinite amplitude, only the area under the curve is finite.

**Comment by rowleya** [comment]
OK, that would make more sense, and explain why our model hasn't worked to date with different time steps.  In that case it should be possible to create a version of it that works correctly but this will need a new implementation as the synapse model needs to work differently than the current models.  I guess "IF_curr_delta" is not quite accurate in that case since the synapses are voltage based rather than current based, but I think we can overlook that for now!
