### ISSUE TITLE
Implement multi-core placement for a single vertex

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/sPyNNaker#85]
This extends the idea of a vertex an allows it to be placed on more than one core if required.

You can represent this is in the current PACMAN system, by having multiple vertices with a PlaceOnSameChipAsConstraint.  There are some advantages to the existing system that I am not entirely sure work well in the new system.  These are:
1. It isn't obvious how the communication works to this vertex from other vertices; it might be that an edge hits every vertex or that an edge hits only one of the vertices (and then which one?)
2. It isn't obvious how the communication works within the vertex.  This might be only via SDRAM, but if it isn't, you need to set up edges within the vertex.

Unless we can solve these problems, we probably shouldn't make this change (so this ticket is just a discussion on this rather than a request for changes as yet).

**Comment by AlexRast** [comment]
Is that how it's always been? My understanding is that a vertex represents a 
graph-level object in model space. Mapped onto cores, this can be split into 
subvertices; these are the things that are mapped to cores specifically.

But, if you are thinking a *subvertex* should also be mappable to several cores, 
again, rather like the idea of an edge with multiple targets, I think this is a 
bad idea because it drifts away from the graph representation.

Using the first terminology, by the way, makes it clear what happens in the case 
of a vertex that later is split amongst multiple cores which need to 
communicate. A vertex is expanded into a subgraph, which itself will contain 
subvertices and subedges. In this approach furthermore, it doesn't matter how 
communication works to a vertex that may later become a subgraph; this is 
handles when the subgraph is exploded - and presumably for a given type of 
vertex there is a CreateSubgraph function which tells the system how to expand 
it into a subgraph with subvertices and subedges.

I'm guessing this is coming up because you're thinking of the MLP...

**Comment by alan-stokes** [comment]
Hi Alex, 

its coming due to jamies plasticity plans, as well as mlp. And on the plasticity points, the subvertices of a vertex need to reside on the same chip for use of sdram transfers. Now we could keep a subvertex as a collection, or split them out. im more for splitting them out and constrainign they all sit on the same chip. whereas there was a thought of using a subvertex to say "i need x cores on a chip" and then leaving the rest to be sorted out downstream, the issue resides when routing orrcurs, as which real subvertex do you tie the incoming and outgoing edges to. This is why breaking it up seems a cleaner approach from my perspective.

**Comment by andrewgait** [comment]
I think this is the kind of thing that @lucaperes is dealing with at the moment.  I'm not sure whether this needs to remain as an issue.

**Comment by rowleya** [comment]
This was similar, but at the PACMAN level; this was the idea that a single machine vertex might be allocated to more than one core.  I personally now don't think that this is a good idea for all the reasons mentioned previously.  It seems also that users are happy with the idea of one-vertex one-core so I think we should leave this as it is.  Anyone who disagrees can reopen this ticket!
