### ISSUE TITLE
removal of cfg database params.

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/sPyNNaker#96]
For the params :

create_database = False
wait_on_confirmation = True
send_start_notification = True
create_routing_info_to_neuron_id_mapping = True

the bottom 3 in theory are never changed and its onyl ever the top one which is adjusted. This could be deduced automatcally thoguh, given that there are only two models which if either is set off, needs this database, and therefore the tool chain could auto detect these and activate database as required.

**Comment by AlexRast** [comment]
I don't know about that. I can easily imagine devices that are unable to send 
any confirmation that they're "alive", so to speak and various other 
applications that might require unusual combinations of these options. I don't 
think it's a given that these would never be changed. Also, a question: if the 
database *is* created, if the wait_on_confirmation option was always true, would 
that mean that DB-creating simulations would *always* have to have a responder 
on the other end that told them to start the simulation? One important use of 
the database is for human inspection of what's been instantiated, possibly for 
off-line analysis but certainly for sanity checks and other such things. It 
would be incredibly annoying to have to create some sort of dummy responder just 
so you could look at the DB! Of course in a larger sense as you know I think the 
purposes of having a DB and the entire idea of having devices query a database 
for information need to be rethought, but that's a separate issue...

**Comment by alan-stokes** [comment]
Hi Alex, 

so we could have the cfg files params set to None, and when thats the case, auto detect, otherwise let the cfg file be dominant. this all came from my slide making and thinking "we dont need these param in the standard case".

On other usages of the database. Its called a input-output database. Not a human readable sanity check database. Theres even consideration to reducing the scope to just the params that are needed to get input output supprot working (thou id admit, i think that would be a step backwards, gven we have no idea what vis's will need what). 

the sdanity checks are done via the reprots, and standard users shouldnt even need to look at those, they dont care how we did things, as long as it worked. You dont go looking into your cars computer every evening to see how well it did the school run.

lets not dive onto the argument of using a database for everything here. Its off topic.

**Comment by AlexRast** [comment]
On 29/06/15 16:02, Alan Stokes wrote:
> Hi Alex,
>
> so we could have the cfg files params set to None, and when thats the case, auto
> detect, otherwise let the cfg file be dominant. this all came from my slide
> making and thinking "we dont need these param in the standard case".

That sounds reasonable. Just to make sure I'm thinking the same thing: if the 
cfg param corresponding to the ones that were proposed to be got rid of in the 
file is present, or is actually set to None in the file, then revert to 
auto-detect. If something is explicitly set, use that. It should be noted that 
if this is done there should be documentation (perhaps just comments in the cfg 
file) indicating the parameters you can set that aren't usually present, and 
what valid values for those are.

> On other usages of the database. Its called a input-output database. Not a human
> readable sanity check database. Theres even consideration to reducing the scope
> to just the params that are needed to get input output supprot working (thou id
> admit, i think that would be a step backwards, gven we have no idea what vis's
> will need what).

Except that *having created* a database, it's actually very useful for human 
sanity checking. That may not have been the original *intent*, but I see no 
reason to get rid of a capability that can be used, when already present.

> the sdanity checks are done via the reprots, and standard users shouldnt even
> need to look at those, they dont care how we did things, as long as it worked.

The problem about the reports is that they provide a very sequential, exhaustive 
display that can take a long time to sift through. The database format is nicely 
"parallel" - it makes it easy to see at a glance what's been done and 
potentially catch things you might not have spotted in a report. Many of these 
will be mis-configurations of a PyNN script (you thought you'd written a script 
that would do X, but in fact it specifies Y). That's very difficult to catch 
using the report mechanism.

> You dont go looking into your cars computer every evening to see how well it did
> the school run.

Only because the car's computer doesn't provide a convenient interface to 
download the data. If it had a USB port on the dashboard, I would definitely be 
interested in downloading the data. It's only because the interface is a 
proprietary one accessible only via special machines at the garage that I don't 
do that.

> lets not dive onto the argument of using a database for everything here. Its off
> topic.

I agree with that! Hence the "that's a separate issue..." comment. However if 
you are referring to the comment about using the database for sanity checking, 
my comment here isn't about extending functionality but only about not 
eliminating already existing capabilities.

**Comment by alan-stokes** [comment]
done and merged with rowley.
