### ISSUE TITLE
Unify branch and cron tests

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/sPyNNaker#976]
As running the integration tests has moved to https://github.com/SpiNNakerManchester/IntegrationTests

Does it still make sense to run different things on branches then on the cron/master?

I would say NO.

Detected by while looking at https://github.com/SpiNNakerManchester/sPyNNaker/pull/958 but out of scope for that PR.

**Comment by rowleya** [comment]
I agree that this is a no.  The integration tests above also run on a cron job.  There are minor differences, but these were done on purpose (for information, the unit tests and coverage is only run within the cron job; the integration tests themselves are run on every branch commit rather than just on a PR).

**Comment by Christian-B** [comment]
I agree that unit test and coverage will remain on cron only.

**Comment by Christian-B** [comment]
done
